import mongoose from 'mongoose';
import fs from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';
import { UserModel } from '../models/User.js';
import { DocumentModel } from '../models/Document.js';
import { QuizModel } from '../models/Quiz.js';
import { ChatModel } from '../models/Chat.js';
import {
  isGibberishText,
  synthesizeEnglishAnalysisFromRag,
  chunkDocumentForRag,
} from '../services/ragService.js';

mongoose.set('bufferCommands', false);

let isMongoConnected = false;

export async function connectDatabase() {
  const uri = process.env.MONGODB_URI;
  if (uri && !uri.includes('localhost/mock')) {
    try {
      await mongoose.connect(uri, {
        serverSelectionTimeoutMS: 2500,
      });
      isMongoConnected = true;
      console.log('[DB] Connected to MongoDB successfully');
      return;
    } catch {
      console.warn('[DB] MongoDB connection unavailable — using persistent local storage adapter');
    }
  }
  isMongoConnected = false;
  ensureLocalStoreInitialized();
}

const DATA_DIR = path.join(process.cwd(), 'server', 'data');
const STORE_FILE = path.join(DATA_DIR, 'store.json');

interface StoreData {
  users: any[];
  documents: any[];
  quizzes: any[];
  chats: any[];
}

function createSeedDocumentsForUser(userId: string) {
  const now = new Date();
  const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 3600 * 1000).toISOString();
  const yesterday = new Date(now.getTime() - 1 * 24 * 3600 * 1000).toISOString();
  const today = now.toISOString();

  const doc1Id = `doc_net_${userId.slice(-6)}`;
  const doc2Id = `doc_mp_${userId.slice(-6)}`;
  const doc3Id = `doc_ml_${userId.slice(-6)}`;

  const documents = [
    {
      _id: doc1Id,
      userId,
      title: 'Computer Networks & Multiplexing — Lecture Notes',
      fileName: 'Computer_Networks_Multiplexing_Unit3.pdf',
      fileType: 'PDF',
      fileSize: 428500,
      extractedText: `UNIT 3: PHYSICAL LAYER, MULTIPLEXING & TRANSMISSION MEDIA
1. Introduction to Multiplexing
Multiplexing is the set of techniques that allows the simultaneous transmission of multiple signals across a single data link. Whenever the bandwidth of a medium linking two devices is greater than the bandwidth needs of the devices, the link can be shared. In a multiplexed system, n lines share the bandwidth of one link. A multiplexer (MUX) combines multiple input streams into a single composite signal, and a demultiplexer (DEMUX) separates the composite signal back into individual component streams at the receiver.

2. Categories of Multiplexing
- Frequency-Division Multiplexing (FDM): An analog technique that can be applied when the bandwidth of a link (in hertz) is greater than the combined bandwidths of the signals to be transmitted. Signals generated by each sending device modulate different carrier frequencies. Guard bands separate adjacent channels to prevent interference.
- Wavelength-Division Multiplexing (WDM): Designed to use the high data rate capability of fiber-optic cable. Conceptually the same as FDM, except that the multiplexing and demultiplexing involve optical signals transmitted through fiber-optic channels using prisms.
- Time-Division Multiplexing (TDM): A digital process that allows several connections to share the high bandwidth of a link by partitioning time into periodic frames and assigning time slots to each channel. Synchronous TDM allocates fixed slots even if a device has no data, whereas Statistical TDM allocates slots dynamically on demand.

3. Channel Capacity & Performance Formulas
- Nyquist Bit Rate (Noiseless Channel): BitRate = 2 * B * log2(L), where B is the bandwidth of the channel and L is the number of signal levels used to represent data.
- Shannon Capacity (Noisy Channel): C = B * log2(1 + SNR), where C is the capacity of the channel in bits per second, B is the bandwidth in Hertz, and SNR is the linear signal-to-noise power ratio.
- Propagation Delay: T_prop = Distance / PropagationSpeed.
- Transmission Delay: T_trans = FrameSize / Bandwidth.

4. Switching Techniques
Circuit Switching establishes a dedicated physical path between two stations before communication begins. Packet Switching divides messages into discrete packets (datagrams or virtual circuits) that are routed independently using store-and-forward mechanisms.`,
      summary: {
        shortSummary:
          'Comprehensive lecture notes covering Physical Layer multiplexing techniques (FDM, WDM, Synchronous & Statistical TDM), channel capacity laws (Nyquist & Shannon theorems), and network switching architectures.',
        detailedSummary:
          'This study unit examines how high-capacity physical communication links are shared among multiple simultaneous transmissions using Multiplexing (MUX/DEMUX). It contrasts analog Frequency-Division Multiplexing (FDM) and optical Wavelength-Division Multiplexing (WDM) with digital Time-Division Multiplexing (TDM). Furthermore, it establishes mathematical limits on data transmission rates across noiseless (Nyquist) and noisy (Shannon) channels, alongside propagation vs. transmission delay formulas and Circuit vs. Packet switching paradigms.',
        keyPoints: [
          'Multiplexing combines multiple input streams via a Multiplexer (MUX) over a single shared physical link and separates them via a Demultiplexer (DEMUX).',
          'Frequency-Division Multiplexing (FDM) partitions channel bandwidth into distinct frequency carrier bands separated by guard bands.',
          'Wavelength-Division Multiplexing (WDM) multiplexes multiple optical light beams of varying wavelengths over a single fiber-optic core.',
          'Time-Division Multiplexing (TDM) divides link time into recurring frames; Statistical TDM avoids wasted empty slots by dynamically assigning slots on demand.',
          'Nyquist theorem defines max bit rate for noiseless channels, while Shannon capacity defines the theoretical upper bound in the presence of Gaussian noise.',
        ],
        formulas: [
          {
            name: 'Shannon Channel Capacity',
            formula: 'C = B × log₂(1 + SNR)',
            description: 'Calculates theoretical maximum bit rate (bps) over a noisy channel with bandwidth B (Hz) and linear Signal-to-Noise Ratio (SNR).',
          },
          {
            name: 'Nyquist Bit Rate',
            formula: 'BitRate = 2 × B × log₂(L)',
            description: 'Determines maximum data rate for a noiseless channel with bandwidth B and L discrete signal levels.',
          },
          {
            name: 'Transmission vs. Propagation Delay',
            formula: 'T_total = (L / R) + (d / v)',
            description: 'Total latency equals packet length L divided by link rate R plus physical distance d divided by wave propagation velocity v.',
          },
        ],
        examples: [
          'AM and FM radio broadcasting stations use FDM to transmit simultaneously over the airwaves on distinct carrier frequencies.',
          'SONET and T-1 carrier lines use Synchronous TDM to interleave digital voice channels into fixed 125-microsecond frames.',
        ],
      },
      importantTopics: [
        {
          name: 'Multiplexing (FDM, WDM, TDM)',
          explanation: 'Sharing a single high-bandwidth physical link across multiple data streams using frequency bands, optical wavelengths, or discrete time slots.',
          importance: 'High',
        },
        {
          name: 'Synchronous vs. Statistical TDM',
          explanation: 'Synchronous TDM reserves fixed time slots regardless of activity, whereas Statistical TDM dynamically allocates slots only to active transmitters with address headers.',
          importance: 'High',
        },
        {
          name: 'Shannon vs. Nyquist Channel Capacity',
          explanation: 'Mathematical bounds governing the maximum achievable data transfer rate over noiseless and noisy communication channels.',
          importance: 'High',
        },
        {
          name: 'Circuit vs. Packet Switching',
          explanation: 'Comparison between dedicated physical reservation (Circuit Switching) and store-and-forward datagram routing (Packet Switching).',
          importance: 'Medium',
        },
      ],
      importantDefinitions: [
        {
          term: 'Multiplexing',
          definition: 'A set of techniques that allows the simultaneous transmission of multiple signals across a single shared data link using a MUX and DEMUX pair.',
          context: 'Section 1: Introduction to Multiplexing',
        },
        {
          term: 'Guard Band',
          definition: 'An unused frequency strip separating adjacent channels in FDM to prevent inter-channel crosstalk and signal interference.',
          context: 'Section 2: Frequency-Division Multiplexing',
        },
        {
          term: 'Statistical TDM',
          definition: 'A time-division multiplexing method where time slots are allocated dynamically on demand only to input lines that currently have data to send.',
          context: 'Section 2: Time-Division Multiplexing',
        },
        {
          term: 'Shannon Capacity',
          definition: 'The theoretical highest data rate in bits per second that can be achieved over a noisy channel of bandwidth B and signal-to-noise ratio SNR.',
          context: 'Section 3: Channel Capacity & Performance',
        },
      ],
      importantQuestions: {
        shortAnswer: [
          {
            question: 'What is multiplexing and why are guard bands necessary in FDM?',
            answerHint: 'Define MUX/DEMUX link sharing and explain how guard bands prevent adjacent carrier frequency overlap.',
          },
          {
            question: 'Differentiate between Synchronous TDM and Statistical TDM.',
            answerHint: 'Compare fixed pre-assigned time slots (which may go empty) against dynamic on-demand slot allocation with addressing.',
          },
          {
            question: 'State the Nyquist Bit Rate formula for a noiseless channel.',
            answerHint: 'BitRate = 2 * B * log2(L), defining B as bandwidth and L as signal levels.',
          },
        ],
        longAnswer: [
          {
            question: 'Compare Frequency-Division Multiplexing (FDM), Wavelength-Division Multiplexing (WDM), and Time-Division Multiplexing (TDM) with neat conceptual breakdowns.',
            keyPointsToInclude: [
              'Analog vs. Digital nature of signals',
              'Domain partitioning: Frequency spectrum vs. Optical prism wavelengths vs. Time frames',
              'Need for guard bands in FDM vs. synchronization framing bits in TDM',
              'Real-world applications of each technique',
            ],
          },
          {
            question: 'Explain how Nyquist and Shannon theorems work together to determine practical channel design limits in data communications.',
            keyPointsToInclude: [
              'Derivation and variables of Shannon Capacity C = B log2(1 + SNR)',
              'Using Shannon to find upper bit rate limit C first',
              'Using Nyquist 2B log2(L) to determine required number of signal levels L',
            ],
          },
        ],
        examOriented: [
          {
            question: 'A noisy channel has a bandwidth of 4 kHz and a linear SNR of 31. Calculate the maximum theoretical Shannon capacity of this channel.',
            marks: '6 Marks',
            frequency: 'High Frequency Exam Problem',
          },
          {
            question: 'Why does Statistical TDM require an explicit destination address in every time slot whereas Synchronous TDM does not?',
            marks: '5 Marks',
            frequency: 'Repeated University Question',
          },
        ],
      },
      savedQuestions: [
        'What is multiplexing and why are guard bands necessary in FDM?',
      ],
      explanationsCache: {
        'Multiplexing (FDM, WDM, TDM)': {
          topic: 'Multiplexing (FDM, WDM, TDM)',
          simpleExplanation:
            'According to your uploaded material, multiplexing is like turning a single wide highway into multiple organized lanes so several cars can travel at the same time without crashing. A Multiplexer (MUX) combines multiple separate signals at the sender side into one shared high-capacity cable, and a Demultiplexer (DEMUX) splits them back apart at the destination.',
          example:
            'In FM radio (FDM), different stations broadcast at the same time through the air using different frequencies (like 98.5 MHz and 101.1 MHz). In TDM, streams take rapid turns sharing 100% of the cable for tiny fractions of a second.',
          keyPoints: [
            'FDM is an analog technique that divides the link bandwidth into distinct frequency channels separated by guard bands.',
            'WDM works like FDM but uses optical light wavelengths combined and split through a prism over fiber-optic cables.',
            'TDM is a digital technique that divides transmission time into recurring frames and time slots.',
          ],
          importantTerms: [
            { term: 'MUX / DEMUX', meaning: 'Multiplexer (combiner) and Demultiplexer (separator) hardware pair.' },
            { term: 'Guard Band', meaning: 'Unused frequency gap between FDM channels to stop interference.' },
          ],
          sourceLabel: 'From your uploaded material',
        },
      },
      sourcePreference: 'pdf_only',
      processingStatus: 'ready',
      createdAt: twoDaysAgo,
      updatedAt: today,
    },
    {
      _id: doc2Id,
      userId,
      title: 'Microprocessors & 8086 Architecture — Study Guide',
      fileName: 'Microprocessors_8086_Architecture.pdf',
      fileType: 'PDF',
      fileSize: 512000,
      extractedText: `MODULE 1: INTRODUCTION TO MICROPROCESSORS & 8086 ARCHITECTURE
1. What is a Microprocessor?
A microprocessor is a multipurpose, clock-driven, register-based, digital integrated circuit (IC) that accepts binary data as input, processes it according to instructions stored in its memory, and provides results (also in binary form) as output. Internally, a microprocessor consists of three foundational functional units: the Arithmetic Logic Unit (ALU), the Register Array, and the Control Unit (CU).

2. 8086 Internal Architecture: BIU and EU
The Intel 8086 microprocessor is a 16-bit processor with a 20-bit address bus (capable of addressing 2^20 = 1 MB of physical memory) and a 16-bit data bus. Its internal architecture is partitioned into two independent functional units that operate in parallel to implement instruction pipelining:
- Bus Interface Unit (BIU): Handles all data and address transfers on the system buses for the Execution Unit. It contains the Segment Registers (CS, DS, SS, ES), the 16-bit Instruction Pointer (IP), the 20-bit physical address adder, and a 6-byte Instruction Prefetch Queue.
- Execution Unit (EU): Decodes and executes instructions fetched by the BIU. It contains the 16-bit ALU, Status and Control Flags Register, General Purpose Registers (AX, BX, CX, DX), and Pointer/Index Registers (SP, BP, SI, DI).

3. Memory Segmentation & Physical Address Calculation
The 1 MB memory space of the 8086 is divided into logical segments of up to 64 KB each: Code Segment (CS), Data Segment (DS), Stack Segment (SS), and Extra Segment (ES).
- Physical Address Formula: Physical Address (20-bit) = (Segment Register × 16) + Effective Offset Address (16-bit). In hexadecimal, multiplying by 16 shifts the segment base left by 4 bits (one hex digit) before adding the 16-bit offset.
- Clock Period Formula: T = 1 / f, where f is the processor clock frequency in Hertz.`,
      summary: {
        shortSummary:
          'Core engineering reference on Microprocessor fundamentals, Intel 8086 pipelined architecture (BIU vs. EU), 1 MB memory segmentation, and 20-bit physical address computation.',
        detailedSummary:
          'This document defines the microprocessor as a clock-driven, register-based programmable integrated circuit comprising an ALU, Control Unit, and Register Array. It details the 16-bit Intel 8086 architecture, explaining how splitting the processor into a Bus Interface Unit (BIU) with a 6-byte prefetch queue and an Execution Unit (EU) enables two-stage instruction pipelining. Finally, it covers 64 KB memory segmentation and the 20-bit physical address formula.',
        keyPoints: [
          'A microprocessor is a clock-driven, register-based digital IC containing an ALU, Control Unit, and Register Array.',
          'The 8086 has a 16-bit data bus and a 20-bit address bus, giving it a 1 MB (2²⁰ bytes) physical memory space.',
          'Splitting 8086 into Bus Interface Unit (BIU) and Execution Unit (EU) allows instruction fetching and execution to happen concurrently (pipelining).',
          'The BIU maintains a 6-byte instruction prefetch queue and four segment registers (CS, DS, SS, ES).',
          '20-bit Physical Address is computed as (Segment Base × 10H) + 16-bit Offset.',
        ],
        formulas: [
          {
            name: '20-Bit Physical Address',
            formula: 'Physical Address = (Segment × 16) + Offset',
            description: 'Shifts the 16-bit segment register left by 4 bits (×10H) and adds the 16-bit effective address offset.',
          },
          {
            name: 'Addressable Memory Space',
            formula: 'Memory Capacity = 2^N bytes',
            description: 'For N = 20 address lines in 8086, total addressable memory is 2²⁰ = 1,048,576 bytes (1 MB).',
          },
        ],
        examples: [
          'If CS = 2000H and IP = 1450H, the Physical Address = (2000H × 10H) + 1450H = 21450H.',
        ],
      },
      importantTopics: [
        {
          name: 'Microprocessor Core Architecture',
          explanation: 'The internal structure of a microprocessor consisting of the ALU, Register Array, and Control Unit working on a system clock.',
          importance: 'Foundational',
        },
        {
          name: 'BIU vs. EU & Pipelining',
          explanation: 'How the Bus Interface Unit prefetches up to 6 bytes of instructions while the Execution Unit decodes and executes prior instructions.',
          importance: 'High',
        },
        {
          name: 'Memory Segmentation in 8086',
          explanation: 'Partitioning 1 MB physical memory into 64 KB logical segments (Code, Data, Stack, Extra) addressed via Segment:Offset pairs.',
          importance: 'High',
        },
      ],
      importantDefinitions: [
        {
          term: 'Microprocessor',
          definition: 'A multipurpose, clock-driven, register-based digital integrated circuit that reads binary instructions from memory, processes binary data, and outputs results.',
          context: 'Section 1: What is a Microprocessor?',
        },
        {
          term: 'Instruction Pipelining',
          definition: 'Overlapping the fetch and execute phases of instruction processing using the 6-byte prefetch queue in the BIU.',
          context: 'Section 2: 8086 Internal Architecture',
        },
        {
          term: 'Memory Segmentation',
          definition: 'Dividing the 1 MB physical address space into logical 64 KB segments pointed to by CS, DS, SS, and ES registers.',
          context: 'Section 3: Memory Segmentation',
        },
      ],
      importantQuestions: {
        shortAnswer: [
          {
            question: 'What is a microprocessor and what are its three primary internal blocks?',
            answerHint: 'Define clock-driven register-based IC and list ALU, Register Array, and Control Unit.',
          },
          {
            question: 'How does the 6-byte prefetch queue in the BIU speed up execution?',
            answerHint: 'It prefetches upcoming instructions while the EU is busy executing the current instruction, eliminating fetch wait time.',
          },
        ],
        longAnswer: [
          {
            question: 'Draw and explain the internal block architecture of the Intel 8086 microprocessor, highlighting the roles of the BIU and EU.',
            keyPointsToInclude: [
              'Bus Interface Unit components: CS, DS, SS, ES, IP, 20-bit address adder, 6-byte queue',
              'Execution Unit components: ALU, Flag register, general purpose registers AX-DX, pointers SP/BP/SI/DI',
              'How parallel operation achieves pipelining',
            ],
          },
        ],
        examOriented: [
          {
            question: 'Given DS = 3400H and SI = 12A4H, calculate the 20-bit physical memory address accessed by the 8086 processor.',
            marks: '5 Marks',
            frequency: 'Every Semester Exam',
          },
        ],
      },
      savedQuestions: [],
      explanationsCache: {},
      sourcePreference: 'pdf_only',
      processingStatus: 'ready',
      createdAt: yesterday,
      updatedAt: yesterday,
    },
    {
      _id: doc3Id,
      userId,
      title: 'Machine Learning & Neural Networks — Core Notes',
      fileName: 'Machine_Learning_Neural_Networks.txt',
      fileType: 'TXT',
      fileSize: 194000,
      extractedText: `CHAPTER 4: NEURAL NETWORKS, BACKPROPAGATION & GRADIENT DESCENT
1. Artificial Neurons and Perceptrons
An artificial neural network (ANN) is a computational model inspired by biological neural networks. The fundamental building block is the perceptron (single neuron), which computes a weighted sum of its inputs z = w·x + b and applies a non-linear activation function a = σ(z).

2. Activation Functions
Non-linear activation functions enable neural networks to learn complex, non-linear decision boundaries:
- Sigmoid: σ(z) = 1 / (1 + e^-z), squashes real numbers into (0, 1). Prone to vanishing gradients for large |z|.
- ReLU (Rectified Linear Unit): f(z) = max(0, z). Computationally efficient and mitigates vanishing gradients in hidden layers.
- Softmax: Converts a vector of raw logits into a normalized probability distribution over K classes.

3. Loss Functions & Gradient Descent Optimization
Training a neural network minimizes a Loss Function J(θ), such as Mean Squared Error (MSE) for regression or Cross-Entropy Loss for classification.
- Gradient Descent Update Rule: θ_{t+1} = θ_t - η * ∇J(θ_t), where η (eta) is the learning rate and ∇J(θ_t) is the gradient of the loss with respect to weights.
- Backpropagation: Uses the chain rule of calculus to efficiently compute partial derivatives ∂J/∂w from the output layer backward through hidden layers.

4. Overfitting & Regularization
Overfitting occurs when a model memorizes training noise and performs poorly on unseen test data. Techniques to prevent overfitting include L2 Weight Decay (Ridge), Dropout (randomly deactivating neurons during training), and Early Stopping.`,
      summary: {
        shortSummary:
          'Concise notes on Artificial Neural Networks, activation functions (Sigmoid, ReLU, Softmax), Gradient Descent optimization, Backpropagation via the chain rule, and regularization techniques.',
        detailedSummary:
          'These notes cover the mathematical foundation of deep learning: how perceptrons compute affine transformations followed by non-linear activations (ReLU, Sigmoid, Softmax), how networks learn by minimizing Cross-Entropy or MSE loss via Gradient Descent, and how Backpropagation applies the chain rule to propagate error gradients backward. It concludes with L2 regularization and Dropout to combat overfitting.',
        keyPoints: [
          'A neuron computes a weighted sum z = w·x + b followed by a non-linear activation function a = f(z).',
          'ReLU f(z) = max(0, z) prevents vanishing gradients in deep hidden layers.',
          'Gradient Descent iteratively updates parameters in the direction opposite to the loss gradient: θ = θ - η∇J(θ).',
          'Backpropagation applies the calculus chain rule from output to input layers to compute weight gradients.',
          'Dropout and L2 regularization prevent overfitting and improve generalization on unseen test data.',
        ],
        formulas: [
          {
            name: 'Gradient Descent Update',
            formula: 'θ_{t+1} = θ_t − η · ∇J(θ_t)',
            description: 'Updates model weights θ using learning rate η and loss gradient ∇J(θ).',
          },
          {
            name: 'ReLU Activation',
            formula: 'f(z) = max(0, z)',
            description: 'Outputs z if positive, and 0 otherwise.',
          },
        ],
        examples: [
          'Using Softmax in the final layer of an image classifier to output probabilities across 10 digit classes.',
        ],
      },
      importantTopics: [
        {
          name: 'Backpropagation & Chain Rule',
          explanation: 'Propagating error derivatives backward from the loss output through hidden layers to update weights.',
          importance: 'High',
        },
        {
          name: 'Activation Functions (ReLU vs Sigmoid)',
          explanation: 'Introducing non-linearity into neural networks while avoiding saturation and vanishing gradients.',
          importance: 'High',
        },
        {
          name: 'Overfitting & Regularization',
          explanation: 'Using Dropout, L2 weight decay, and Early Stopping so models generalize to unseen test sets.',
          importance: 'Medium',
        },
      ],
      importantDefinitions: [
        {
          term: 'Learning Rate (η)',
          definition: 'A hyperparameter that controls the step size taken toward the minimum of the loss function during gradient descent.',
          context: 'Section 3: Gradient Descent Optimization',
        },
        {
          term: 'Overfitting',
          definition: 'When a machine learning model fits training data too closely (including noise) and fails to generalize to new data.',
          context: 'Section 4: Overfitting & Regularization',
        },
      ],
      importantQuestions: {
        shortAnswer: [
          {
            question: 'Why is a non-linear activation function necessary in hidden layers of a neural network?',
            answerHint: 'Without non-linearity, stacking multiple linear layers collapses into a single linear transformation.',
          },
        ],
        longAnswer: [
          {
            question: 'Explain the Backpropagation algorithm and how Gradient Descent updates neural network weights.',
            keyPointsToInclude: [
              'Forward pass computation of activations and loss J(θ)',
              'Backward pass using chain rule ∂J/∂w',
              'Weight update equation with learning rate η',
            ],
          },
        ],
        examOriented: [
          {
            question: 'Compare Sigmoid and ReLU activation functions with respect to the vanishing gradient problem.',
            marks: '6 Marks',
            frequency: 'High Frequency Exam Question',
          },
        ],
      },
      savedQuestions: [],
      explanationsCache: {},
      sourcePreference: 'pdf_only',
      processingStatus: 'ready',
      createdAt: today,
      updatedAt: today,
    },
  ];

  const quizzes = [
    {
      _id: `quiz_net_${userId.slice(-6)}`,
      userId,
      documentId: doc1Id,
      documentTitle: 'Computer Networks & Multiplexing — Lecture Notes',
      title: 'Multiplexing & Channel Capacity Mastery Quiz',
      questions: [
        {
          question: 'Which multiplexing technique partitions the frequency spectrum of a link into distinct carrier bands separated by guard bands?',
          options: [
            'Frequency-Division Multiplexing (FDM)',
            'Synchronous Time-Division Multiplexing (TDM)',
            'Statistical Time-Division Multiplexing',
            'Packet Switching Multiplexing',
          ],
          correctAnswer: 0,
          explanation: 'According to your study material, FDM is an analog multiplexing method that assigns each signal a different carrier frequency separated by guard bands to prevent interference.',
        },
        {
          question: 'Why is Statistical TDM more bandwidth-efficient than Synchronous TDM when traffic is bursty?',
          options: [
            'It uses optical prisms instead of copper wires',
            'It allocates time slots dynamically on demand only to active devices',
            'It eliminates the need for addressing information in slots',
            'It increases the physical propagation velocity of the cable',
          ],
          correctAnswer: 1,
          explanation: 'Synchronous TDM reserves fixed time slots even when a device has no data to send, whereas Statistical TDM dynamically assigns slots only when an input line has data ready.',
        },
        {
          question: 'Which formula gives the theoretical maximum data rate of a noisy channel with bandwidth B and signal-to-noise ratio SNR?',
          options: [
            'C = 2 × B × log₂(L)',
            'C = B × log₂(1 + SNR)',
            'C = FrameSize / Bandwidth',
            'C = B / (1 + SNR)',
          ],
          correctAnswer: 1,
          explanation: 'Shannon Capacity (C = B × log₂(1 + SNR)) defines the theoretical upper bound in bps for a noisy channel.',
        },
        {
          question: 'In Wavelength-Division Multiplexing (WDM), what physical component is typically used to combine and split multiple optical signals?',
          options: [
            'A store-and-forward router',
            'An optical prism',
            'A low-pass RC filter',
            'A 16-bit instruction pointer',
          ],
          correctAnswer: 1,
          explanation: 'WDM multiplexes and demultiplexes optical light signals of different wavelengths through fiber-optic channels using optical prisms.',
        },
        {
          question: 'According to the Nyquist Bit Rate formula (BitRate = 2 * B * log2(L)), if a noiseless channel uses L = 4 signal levels and has bandwidth B = 3000 Hz, what is the maximum bit rate?',
          options: [
            '3,000 bps',
            '6,000 bps',
            '12,000 bps',
            '24,000 bps',
          ],
          correctAnswer: 2,
          explanation: 'Using BitRate = 2 × 3000 × log₂(4) = 6000 × 2 = 12,000 bps.',
        },
      ],
      score: 4,
      totalQuestions: 5,
      percentage: 80,
      userAnswers: [0, 1, 1, 1, 0],
      completedAt: yesterday,
      createdAt: twoDaysAgo,
    },
    {
      _id: `quiz_mp_${userId.slice(-6)}`,
      userId,
      documentId: doc2Id,
      documentTitle: 'Microprocessors & 8086 Architecture — Study Guide',
      title: 'Intel 8086 Architecture & Memory Segmentation Quiz',
      questions: [
        {
          question: 'Which unit inside the Intel 8086 microprocessor contains the 6-byte Instruction Prefetch Queue and Segment Registers?',
          options: [
            'Execution Unit (EU)',
            'Bus Interface Unit (BIU)',
            'Arithmetic Logic Unit (ALU)',
            'DMA Controller Unit',
          ],
          correctAnswer: 1,
          explanation: 'The Bus Interface Unit (BIU) manages all external bus transfers, segment registers (CS, DS, SS, ES), the Instruction Pointer, and the 6-byte instruction prefetch queue.',
        },
        {
          question: 'How many address lines does the Intel 8086 microprocessor have, and what is its total physical memory capacity?',
          options: [
            '16 address lines; 64 KB capacity',
            '20 address lines; 1 MB capacity',
            '24 address lines; 16 MB capacity',
            '32 address lines; 4 GB capacity',
          ],
          correctAnswer: 1,
          explanation: 'The 8086 has a 20-bit address bus, allowing it to address 2²⁰ = 1,048,576 bytes (1 MB) of physical memory.',
        },
        {
          question: 'How is the 20-bit Physical Address calculated from a 16-bit Segment register and a 16-bit Offset in the 8086?',
          options: [
            'Physical Address = Segment + Offset',
            'Physical Address = (Segment × 16) + Offset',
            'Physical Address = (Offset × 16) + Segment',
            'Physical Address = Segment × Offset',
          ],
          correctAnswer: 1,
          explanation: 'The BIU shifts the 16-bit segment register left by 4 bits (multiplying by 16 or 10H) and adds the 16-bit effective offset address.',
        },
        {
          question: 'What are the three foundational internal functional units of a generic microprocessor?',
          options: [
            'ALU, Register Array, and Control Unit',
            'Hard Disk, RAM, and PCI Bus',
            'Compiler, Assembler, and Linker',
            'Multiplexer, Demultiplexer, and Prism',
          ],
          correctAnswer: 0,
          explanation: 'According to Section 1 of your study material, a microprocessor consists of the Arithmetic Logic Unit (ALU), Register Array, and Control Unit (CU).',
        },
      ],
      score: 4,
      totalQuestions: 4,
      percentage: 100,
      userAnswers: [1, 1, 1, 0],
      completedAt: today,
      createdAt: yesterday,
    },
  ];

  const chats = [
    {
      _id: `chat_net_${userId.slice(-6)}`,
      userId,
      documentId: doc1Id,
      sourceMode: 'pdf_only',
      messages: [
        {
          id: 'msg_welcome_1',
          role: 'assistant',
          content:
            'Hello! I am your Source-First AI Tutor for **Computer Networks & Multiplexing — Lecture Notes**. Ask me anything about multiplexing (FDM, WDM, TDM), channel capacity formulas, or switching techniques. I will check your uploaded study material first.',
          sourceType: 'system',
          sourceLabel: 'Source-First AI Tutor Ready',
          timestamp: twoDaysAgo,
        },
        {
          id: 'msg_demo_u1',
          role: 'user',
          content: 'Explain multiplexing.',
          sourceType: 'pdf',
          timestamp: yesterday,
        },
        {
          id: 'msg_demo_a1',
          role: 'assistant',
          content:
            'According to your uploaded material (**Section 1: Introduction to Multiplexing & Section 2: Categories of Multiplexing**), **multiplexing** is the set of techniques that allows the simultaneous transmission of multiple signals across a single shared data link whenever the bandwidth of the medium exceeds the needs of individual devices.\n\n### How it Works\n- **Multiplexer (MUX):** Combines $n$ separate input lines into a single high-bandwidth composite signal at the transmitter.\n- **Demultiplexer (DEMUX):** Separates the composite stream back into individual component signals at the receiver.\n\n### Three Main Categories in Your Notes\n1. **Frequency-Division Multiplexing (FDM):** An analog method that assigns each signal a distinct carrier frequency band separated by unused **guard bands**.\n2. **Wavelength-Division Multiplexing (WDM):** An optical method for fiber-optic cables that combines and splits light wavelengths through a prism.\n3. **Time-Division Multiplexing (TDM):** A digital method that partitions link time into recurring frames and time slots (**Synchronous TDM** uses fixed slots; **Statistical TDM** assigns slots dynamically on demand).',
          sourceType: 'pdf',
          sourceLabel: 'From your uploaded material',
          relevantSection: 'Section 1 & Section 2: Multiplexing (FDM, WDM, TDM)',
          timestamp: yesterday,
        },
      ],
      createdAt: twoDaysAgo,
      updatedAt: yesterday,
    },
  ];

  return { documents, quizzes, chats };
}

function ensureLocalStoreInitialized(): StoreData {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
  if (!fs.existsSync(STORE_FILE)) {
    const demoUserId = 'user_demo_alex_2026';
    const passwordHash = bcrypt.hashSync('password123', 10);
    const seed = createSeedDocumentsForUser(demoUserId);
    const initialData: StoreData = {
      users: [
        {
          _id: demoUserId,
          name: 'Alex Rivera',
          email: 'alex@university.edu',
          passwordHash,
          createdAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
        },
      ],
      documents: seed.documents,
      quizzes: seed.quizzes,
      chats: seed.chats,
    };
    fs.writeFileSync(STORE_FILE, JSON.stringify(initialData, null, 2), 'utf-8');
    return initialData;
  }
  try {
    const raw = fs.readFileSync(STORE_FILE, 'utf-8');
    const parsed = JSON.parse(raw) as StoreData;
    let modified = false;

    // Self-heal any documents that previously had raw PDF binary/ASCII85 streams or incomplete definitions
    if (Array.isArray(parsed.documents)) {
      parsed.documents = parsed.documents.map((doc) => {
        const hasEmptyDef =
          Array.isArray(doc.importantDefinitions) &&
          doc.importantDefinitions.some((d: any) => !d.definition || d.definition.length < 20);
        if (
          isGibberishText(doc.extractedText) ||
          isGibberishText(doc.summary?.shortSummary) ||
          hasEmptyDef
        ) {
          const repaired = synthesizeEnglishAnalysisFromRag(doc.title || 'Study Material', '');
          modified = true;
          return {
            ...doc,
            extractedText: repaired.cleanText,
            ragChunks: repaired.ragChunks,
            summary: repaired.summary,
            importantTopics: repaired.importantTopics,
            importantDefinitions: repaired.importantDefinitions,
            importantQuestions: repaired.importantQuestions,
            explanationsCache: {},
          };
        }
        if (!Array.isArray(doc.ragChunks) || doc.ragChunks.length === 0) {
          modified = true;
          return {
            ...doc,
            ragChunks: chunkDocumentForRag(doc.extractedText, doc.title || 'Study Material'),
          };
        }
        return doc;
      });
    }

    // Self-heal any quizzes whose questions or options contained PDF binary stream noise or empty options
    if (Array.isArray(parsed.quizzes)) {
      parsed.quizzes = parsed.quizzes.map((quiz) => {
        const hasCorruptedQuestion =
          Array.isArray(quiz.questions) &&
          quiz.questions.some(
            (q: any) =>
              isGibberishText(q.question) ||
              (Array.isArray(q.options) &&
                q.options.some((opt: string) => !opt || opt.length < 5 || isGibberishText(opt)))
          );
        if (hasCorruptedQuestion) {
          const repaired = synthesizeEnglishAnalysisFromRag(
            quiz.documentTitle || quiz.title || 'Study Material',
            ''
          );
          modified = true;
          return {
            ...quiz,
            questions: repaired.quizQuestions,
            totalQuestions: repaired.quizQuestions.length,
          };
        }
        return quiz;
      });
    }

    if (modified) {
      fs.writeFileSync(STORE_FILE, JSON.stringify(parsed, null, 2), 'utf-8');
    }
    return parsed;
  } catch {
    return { users: [], documents: [], quizzes: [], chats: [] };
  }
}

function readLocalStore(): StoreData {
  return ensureLocalStoreInitialized();
}

function writeLocalStore(data: StoreData) {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
  fs.writeFileSync(STORE_FILE, JSON.stringify(data, null, 2), 'utf-8');
}

export const dbStore = {
  // USER OPERATIONS
  async findUserByEmail(email: string) {
    const cleanEmail = email.toLowerCase().trim();
    if (isMongoConnected) {
      return await UserModel.findOne({ email: cleanEmail }).lean();
    }
    const store = readLocalStore();
    return store.users.find((u) => u.email.toLowerCase() === cleanEmail) || null;
  },

  async findUserById(id: string) {
    if (isMongoConnected) {
      return await UserModel.findById(id).lean();
    }
    const store = readLocalStore();
    return store.users.find((u) => u._id === id) || null;
  },

  async createUser(name: string, email: string, passwordHash: string) {
    const cleanEmail = email.toLowerCase().trim();
    if (isMongoConnected) {
      const created = await UserModel.create({ name, email: cleanEmail, passwordHash });
      const userObj = created.toObject();
      const seed = createSeedDocumentsForUser(String(userObj._id));
      await DocumentModel.insertMany(seed.documents.map(({ _id, ...rest }) => rest));
      return userObj;
    }
    const store = readLocalStore();
    const newUser = {
      _id: `user_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      name: name.trim(),
      email: cleanEmail,
      passwordHash,
      createdAt: new Date().toISOString(),
    };
    store.users.push(newUser);
    // Seed initial engineering documents so new student has both sample materials and ability to upload new ones
    const seed = createSeedDocumentsForUser(newUser._id);
    store.documents.push(...seed.documents);
    store.quizzes.push(...seed.quizzes);
    store.chats.push(...seed.chats);
    writeLocalStore(store);
    return newUser;
  },

  async updateUser(id: string, updates: { name?: string; passwordHash?: string }) {
    if (isMongoConnected) {
      return await UserModel.findByIdAndUpdate(id, updates, { new: true }).lean();
    }
    const store = readLocalStore();
    const idx = store.users.findIndex((u) => u._id === id);
    if (idx === -1) return null;
    store.users[idx] = { ...store.users[idx], ...updates };
    writeLocalStore(store);
    return store.users[idx];
  },

  // DOCUMENT OPERATIONS
  async getDocumentsByUser(userId: string) {
    if (isMongoConnected) {
      return await DocumentModel.find({ userId }).sort({ createdAt: -1 }).lean();
    }
    const store = readLocalStore();
    return store.documents
      .filter((d) => d.userId === userId)
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  },

  async getDocumentById(id: string, userId: string) {
    if (isMongoConnected) {
      return await DocumentModel.findOne({ _id: id, userId }).lean();
    }
    const store = readLocalStore();
    return store.documents.find((d) => d._id === id && d.userId === userId) || null;
  },

  async createDocument(docData: any) {
    if (isMongoConnected) {
      const created = await DocumentModel.create(docData);
      return created.toObject();
    }
    const store = readLocalStore();
    const now = new Date().toISOString();
    const newDoc = {
      _id: `doc_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      ...docData,
      savedQuestions: docData.savedQuestions || [],
      explanationsCache: docData.explanationsCache || {},
      sourcePreference: docData.sourcePreference || 'pdf_only',
      processingStatus: 'ready',
      createdAt: now,
      updatedAt: now,
    };
    store.documents.unshift(newDoc);
    writeLocalStore(store);
    return newDoc;
  },

  async updateDocument(id: string, userId: string, updates: any) {
    if (isMongoConnected) {
      return await DocumentModel.findOneAndUpdate(
        { _id: id, userId },
        { ...updates, updatedAt: new Date() },
        { new: true }
      ).lean();
    }
    const store = readLocalStore();
    const idx = store.documents.findIndex((d) => d._id === id && d.userId === userId);
    if (idx === -1) return null;
    store.documents[idx] = {
      ...store.documents[idx],
      ...updates,
      updatedAt: new Date().toISOString(),
    };
    writeLocalStore(store);
    return store.documents[idx];
  },

  async deleteDocument(id: string, userId: string) {
    if (isMongoConnected) {
      await QuizModel.deleteMany({ documentId: id, userId });
      await ChatModel.deleteMany({ documentId: id, userId });
      const res = await DocumentModel.findOneAndDelete({ _id: id, userId });
      return !!res;
    }
    const store = readLocalStore();
    const initialLen = store.documents.length;
    store.documents = store.documents.filter((d) => !(d._id === id && d.userId === userId));
    store.quizzes = store.quizzes.filter((q) => !(q.documentId === id && q.userId === userId));
    store.chats = store.chats.filter((c) => !(c.documentId === id && c.userId === userId));
    writeLocalStore(store);
    return store.documents.length < initialLen;
  },

  // QUIZ OPERATIONS
  async getQuizzesByUser(userId: string) {
    if (isMongoConnected) {
      return await QuizModel.find({ userId }).sort({ createdAt: -1 }).lean();
    }
    const store = readLocalStore();
    return store.quizzes
      .filter((q) => q.userId === userId)
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  },

  async getQuizById(id: string, userId: string) {
    if (isMongoConnected) {
      return await QuizModel.findOne({ _id: id, userId }).lean();
    }
    const store = readLocalStore();
    return store.quizzes.find((q) => q._id === id && q.userId === userId) || null;
  },

  async createQuiz(quizData: any) {
    if (isMongoConnected) {
      const created = await QuizModel.create(quizData);
      return created.toObject();
    }
    const store = readLocalStore();
    const newQuiz = {
      _id: `quiz_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      ...quizData,
      score: quizData.score ?? null,
      percentage: quizData.percentage ?? null,
      userAnswers: quizData.userAnswers || [],
      completedAt: quizData.completedAt || null,
      createdAt: new Date().toISOString(),
    };
    store.quizzes.unshift(newQuiz);
    writeLocalStore(store);
    return newQuiz;
  },

  async updateQuiz(id: string, userId: string, updates: any) {
    if (isMongoConnected) {
      return await QuizModel.findOneAndUpdate({ _id: id, userId }, updates, { new: true }).lean();
    }
    const store = readLocalStore();
    const idx = store.quizzes.findIndex((q) => q._id === id && q.userId === userId);
    if (idx === -1) return null;
    store.quizzes[idx] = { ...store.quizzes[idx], ...updates };
    writeLocalStore(store);
    return store.quizzes[idx];
  },

  // CHAT OPERATIONS
  async getChatByDocument(documentId: string, userId: string) {
    if (isMongoConnected) {
      return await ChatModel.findOne({ documentId, userId }).lean();
    }
    const store = readLocalStore();
    return store.chats.find((c) => c.documentId === documentId && c.userId === userId) || null;
  },

  async saveOrUpdateChat(
    documentId: string,
    userId: string,
    messages: any[],
    sourceMode: 'pdf_only' | 'pdf_and_external'
  ) {
    if (isMongoConnected) {
      const existing = await ChatModel.findOne({ documentId, userId });
      if (existing) {
        existing.messages = messages;
        existing.sourceMode = sourceMode;
        await existing.save();
        return existing.toObject();
      }
      const created = await ChatModel.create({
        documentId,
        userId,
        messages,
        sourceMode,
      });
      return created.toObject();
    }
    const store = readLocalStore();
    const now = new Date().toISOString();
    const idx = store.chats.findIndex((c) => c.documentId === documentId && c.userId === userId);
    if (idx !== -1) {
      store.chats[idx] = {
        ...store.chats[idx],
        messages,
        sourceMode,
        updatedAt: now,
      };
      writeLocalStore(store);
      return store.chats[idx];
    }
    const newChat = {
      _id: `chat_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      documentId,
      userId,
      messages,
      sourceMode,
      createdAt: now,
      updatedAt: now,
    };
    store.chats.push(newChat);
    writeLocalStore(store);
    return newChat;
  },

  async clearChat(documentId: string, userId: string, docTitle: string, sourceMode: 'pdf_only' | 'pdf_and_external') {
    const initialMessages = [
      {
        id: `msg_welcome_${Date.now()}`,
        role: 'assistant',
        content: `Conversation cleared. I am ready to answer questions about **${docTitle}**. I will check your uploaded study material first.`,
        sourceType: 'system',
        sourceLabel: 'Source-First AI Tutor Ready',
        timestamp: new Date().toISOString(),
      },
    ];
    return await this.saveOrUpdateChat(documentId, userId, initialMessages, sourceMode);
  },
};
